# This script takes projections generated by plot_projections_lonlat.R and plots them nicely
###############################################################################

library(raster)
library(ggplot2)
library(rgeos)
library(rgdal)

load('SDM_Callipogon.RData')

#preparing map polygons to ggplot
ext_latlon = extent(stack('C.relictus/proj_C_relictus_ll__present/proj_C_relictus_ll__present_C.relictus_ensemble.grd'))
sm_ll_map = crop(ll_map, ext_latlon + c(-10,10,-10,10))
map.points = fortify(sm_ll_map)




#read weighted average ensemble projection for present, removing islands
area_to_mask = readOGR('./islands_exclude/islands.kml','islands') #mask islands from environmental data
proj_EM_ll = mask(stack('C.relictus/proj_C_relictus_ll__present/proj_C_relictus_ll__present_C.relictus_ensemble.grd'), area_to_mask, inverse = T)
#convert raster to points for plotting weighted mean
plot_data = data.frame(rasterToPoints(proj_EM_ll[[c(6,7)]]))
names(plot_data) = c('Longitude','Latitude','Committee_Averaging','Weighted_Mean')
ggplot(plot_data) + 
    geom_raster(aes(Longitude, Latitude, fill=Weighted_Mean)) +
    geom_path(aes(long,lat,group=group), data = map.points) +
    coord_fixed(ratio = 2, xlim =c(110, 140), ylim = c(31,55)) +
    scale_fill_gradientn(colours = c('#4575b4','#ffffbf', '#d73027'))


plot_data_multiple = cbind(plot_data[c(1,2)],
                         list(Method = factor(rep(c('Committee averaging', 'Weighted Mean'),each=dim(plot_data)[1]))), 
                         list(Probability=c(plot_data[[3]],plot_data[[4]])))

base_plot = ggplot(plot_data_multiple) + 
              geom_raster(aes(Longitude, Latitude, fill=Probability)) +
              geom_path(aes(long,lat,group=group), data = map.points) +
              coord_fixed(ratio = 1, xlim =c(110, 140), ylim = c(31,55)) +
              scale_fill_gradientn(colours = c('#4575b4','#ffffbf', '#d73027')) +
              theme(panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_rect(fill = "ghostwhite"))
base_plot + facet_grid(.~Method)


#make a graph showing committee averaging, weighted mea, present and future
proj_EM_ll_fut = mask(stack('C.relictus/proj_C_relictus_ll__future_J_worst/proj_C_relictus_ll__future_J_worst_C.relictus_ensemble.grd'), area_to_mask, inverse = T)
#convert raster to points for plotting weighted mean
plot_data_future = data.frame(rasterToPoints(proj_EM_ll_fut[[c(6,7)]]))
names(plot_data_future) = c('Longitude','Latitude','F_Committee_Averaging','F_Weighted_Mean')





plot_data_all=merge(plot_data,plot_data_future)
plot_data_all_multiple = cbind(plot_data_all[c(1,2)],
                               list(Scenario=factor(rep(c('Present','2050'),each=2*dim(plot_data_all)[1]),ordered = T, levels = c('Present','2050'))),
                           list(Method = factor(rep(c('Committee averaging', 'Weighted Mean'),each=dim(plot_data_all)[1]))), 
                           list(Probability=c(plot_data_all[[3]],plot_data_all[[4]],plot_data_all[[5]],plot_data_all[[6]])))

pdf('map_projections.pdf',width = 7, height = 7)
base_plot = ggplot(plot_data_all_multiple) + 
  geom_raster(aes(Longitude, Latitude, fill=Probability)) +
  geom_path(aes(long,lat,group=group), data = map.points) +
  coord_fixed(ratio = 1.367336*24/30, xlim =c(110, 140), ylim = c(31,55)) +
  scale_fill_gradientn(colours = c('#4575b4','#ffffbf', '#d73027')) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "ghostwhite")) +
  geom_point(aes(x = longitude, y = latitude), data = as.data.frame(spTransform(utm_subs, CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0 "))), pch = 21, colour = 'black', fill = "cornsilk2", size = 0.8)
print(base_plot + facet_grid(Method~Scenario))
dev.off()


##function that I saw on stackoverflow to calculate aspect ratio - not sure if I have to multiply result by 24/30, but looks good
map_aspect = function(x, y) {
  x.center <- sum(range(x)) / 2
  y.center <- sum(range(y)) / 2
  x.dist <- ggplot2:::dist_central_angle(x.center + c(-0.5, 0.5), rep(y.center, 2))
  y.dist <- ggplot2:::dist_central_angle(rep(x.center, 2), y.center + c(-0.5, 0.5))
  y.dist / x.dist
}

map_aspect(c(110, 140),c(31,55))