# This script takes models generated by SDM_Callipogon.R
# Projects them into binary form
# And calculates area lost/gained

###############################################################################
# 1 - load packages
library(biomod2)
library(rworldmap)
library(rgdal)
library(rgeos)

# 2 - load previous run and save S Korea
load("SDM_Callipogon.RData")
TSS_values = get_evaluations(biomod_modelsout)['TSS','Testing.data',,,]
korea_map = utm_map@polygons[which(sapply(utm_map@polygons,function(x){x@ID == 'South Korea'}))]
korea_map = SpatialPolygons(korea_map,proj4string = utm_map@proj4string)

# 3 - make a data frame to save results to build graphs
results_expansion = data.frame(expand_global = NULL,
                               loss_global = NULL,
                               expand_S_Korea = NULL,
                               loss_S_Korea = NULL,
                               modeling_group = NULL,
                               RCP = NULL,
                               method = NULL,
                               run = NULL,
                               TSS = NULL)

# 4 - get predictions to present
predictions_present = stack('C.relictus/proj_C_relictus_current/proj_C_relictus_current_C.relictus.grd')


# 5 - for each future scenario, recover predictions and compare to present
for (scenario in list(list(name = 'future_K_best', data = future_K_best, rcp = 2.6, modelling_group = 'HadGEM2-AO'),
                      list(name = 'future_J_best', data = future_J_best, rcp = 2.6, modelling_group = 'MIROC5'),
                      list(name = 'future_C_best', data = future_C_best, rcp = 2.6, modelling_group = 'BCC-CSM1-1'),
                      list(name = 'future_K_worst', data = future_K_worst, rcp = 8.5, modelling_group = 'HadGEM2-AO'),
                      list(name = 'future_J_worst', data = future_J_worst, rcp = 8.5, modelling_group = 'MIROC5'),
                      list(name = 'future_C_worst', data = future_C_worst, rcp = 8.5, modelling_group = 'BCC-CSM1-1'))){
  predictions_future = stack(paste('C.relictus/proj_C_relictus_',
                              scenario$name,
                              '/proj_C_relictus_',
                              scenario$name,
                              '_C.relictus.grd',
                              sep = ''))
  
  prediction_names = sapply(predictions_present@layers,function(x){names(x[[1]])})
  
  for (run_name in dimnames(get_evaluations(biomod_modelsout))[[4]]){
    for (inf_method in dimnames(get_evaluations(biomod_modelsout))[[3]]){
      i_TSS = TSS_values[inf_method,run_name]
      if (!(is.na(i_TSS))){
          name_layer = paste('C.relictus_PA1',run_name,inf_method,sep="_")
          future_layer = BinaryTransformation(predictions_future@layers[[which(prediction_names == name_layer)]],get_evaluations(biomod_modelsout)['TSS','Cutoff',inf_method,run_name,'PA1']/1000)
          present_layer = BinaryTransformation(predictions_present@layers[[which(prediction_names == name_layer)]],get_evaluations(biomod_modelsout)['TSS','Cutoff',inf_method,run_name,'PA1']/1000)
          
          plot(stack(list(future_layer,present_layer)))
            
          n_present_global = sum(as.array(present_layer),na.rm=T)
          n_present_korea = sum(as.array(mask(present_layer, korea_map)), na.rm = T)
          
          n_expand = sum((future_layer > present_layer)@data@values, na.rm=T)/n_present_global
          n_expand_korea = sum((mask(future_layer > present_layer, korea_map))@data@values, na.rm=T)/n_present_korea
          n_loss = sum((future_layer < present_layer)@data@values, na.rm=T)/n_present_global
          n_loss_korea = sum((mask(future_layer < present_layer, korea_map))@data@values, na.rm=T)/n_present_korea
    
          results_expansion = rbind(results_expansion,data.frame(expand_global = n_expand,
                                                                 loss_global = n_loss,
                                                                 expand_S_Korea = n_expand_korea,
                                                                 loss_S_Korea = n_loss_korea,
                                                                 modeling_group = scenario$modelling_group,
                                                                 RCP = scenario$rcp,
                                                                 method = inf_method,
                                                                 run = run_name,
                                                                 TSS = i_TSS))
        }
    }
  }
}


results_good = results_expansion[results_expansion$TSS>0.75,]


pdf('area_expansion.pdf',height = 4, width = 6)
p = ggplot(data = results_good) +
  geom_point(aes(x = 100*loss_global, y = 100*expand_global, shape = modeling_group)) +
  geom_abline(slope = 1, intercept = 0)
p + 
  facet_grid(.~ RCP, labeller = as_labeller(c('85' = 'RCP 8.5', '26' = 'RCP 2.6'))) +
  guides(shape = guide_legend(title = 'Climate model')) + 
  theme_classic() +
  theme(legend.position = 'bottom') +
  labs(x = 'Area loss (%)', y = 'Area expansion (%)')
dev.off()

pdf('sup_area_expansion_korea.pdf',height = 4, width = 6)
p = ggplot(data = results_good) +
  geom_point(aes(x = 100*loss_S_Korea, y = 100*expand_S_Korea, shape = modeling_group)) +
  geom_abline(slope = 1, intercept = 0)
p + 
  facet_grid(.~ RCP, labeller = as_labeller(c('85' = 'RCP 8.5', '26' = 'RCP 2.6'))) +
  guides(shape = guide_legend(title = 'Climate model')) + 
  theme_classic() +
  theme(legend.position = 'bottom') +
  labs(title = 'Predicted changes for S. Korea', x = 'Area loss (%)', y = 'Area expansion (%)')
dev.off()

save.image("SDM_Callipogon.RData")
